
version: 2

models:
  - name: cines
    description: "Transformacion de raw_cine"
    columns:
      - name: cod_localidad
        tests:
          - unique
          - not_null
      - name: id_provincia
        tests:
          - unique
          - not_null
      - name: id_departamento
        tests:
          - unique
          - not_null
      - name: provincia
      - name: categoria
      - name: domicilio
      - name: codigo_postal
      - name: localidad
      - name: nombre
      - name: telefono
      - name: mail
      - name: web

  - name: bibliotecas
    description: "Transformacion de raw_biblioteca"
    columns:
      - name: cod_localidad
        tests:
          - unique
          - not_null
      - name: id_provincia
        tests:
          - unique
          - not_null
      - name: id_departamento
        tests:
          - unique
          - not_null
      - name: provincia
      - name: categoria
      - name: domicilio
      - name: codigo_postal
      - name: localidad
      - name: nombre
      - name: telefono
      - name: mail
      - name: web

  - name: museos
    description: "Transformacion de raw_museo"
    columns:
      - name: cod_localidad
        tests:
          - unique
          - not_null
      - name: id_provincia
        tests:
          - unique
          - not_null
      - name: id_departamento
        tests:
          - unique
          - not_null
      - name: provincia
      - name: categoria
      - name: domicilio
      - name: codigo_postal
      - name: localidad
      - name: nombre
      - name: telefono
      - name: mail
      - name: web
  
  - name: cines_insights
    description: "Cantidad de butacas, pantallas y espacios INCAA por provincia"
    columns:
      - name: provincia
      - name: pantallas
      - name: butacas
      - name: espacios_incaa

  - name: size_by_category
    description: "Registros por categoria"
    columns:
      - name: categoria
      - name: cantidad

  - name: size_by_category_province
    description: "Registros por categoria y provincia"
    columns:
      - name: categoria
      - name: provincia
      - name: cantidad