version: '3.8'

# TODO: Try to keep just one docker compose file in the root path directory and not multiple docker compose files (see docker compose network to connect them)
services:
  s3_minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: minio_admin
      MINIO_SECRET_KEY: minio_password
    command: server /data --console-address ":9090" 
    restart: always

  s3_minio_buckets:
    image: minio/mc
    depends_on:
        - s3_minio
    entrypoint: >
        /bin/sh -c "
        /usr/bin/mc config host add s3_minio http://host.docker.internal:9000 minio_admin minio_password;
        /usr/bin/mc rm -r --force s3_minio/raw;
        /usr/bin/mc mb s3_minio/raw;
        /usr/bin/mc rm -r --force s3_minio/dbt;
        /usr/bin/mc mb s3_minio/dbt;
        exit 0;
        "
volumes:
  minio_storage: